const PROFILE_IDS = {
  GENERIC: "generic",
  DNS_ATTACK: "dns_attack",
  DYNAMIC_RESOLUTION: "dynamic_resolution",
  NETWORK_SNIFFING: "network_sniffing",
  SESSION_HIJACKING: "session_hijacking",
  CREDENTIAL_THEFT: "credential_theft",
  EXPLOITATION_REMOTE_SERVICES: "exploitation_remote_services",
  EXTERNAL_REMOTE_SERVICES: "external_remote_services",
  RESOURCE_FORKING: "resource_forking",
  PASSWORD_CRACKING: "password_cracking",
  PASSWORD_GUESSING: "password_guessing",
  PASSWORD_SPRAYING: "password_spraying",
  DISABLE_OR_MODIFY_TOOLS: "disable_or_modify_tools",
  SCHEDULED_TASK: "scheduled_task",
  KERBEROS_TICKET: "kerberos_ticket",
  PASS_THE_HASH: "pass_the_hash",
  DCSYNC: "dcsync",
  LSASS_MEMORY: "lsass_memory",
  CREDENTIAL_DUMPING: "credential_dumping",
  RDP_HIJACKING: "rdp_hijacking",
  PHISHING_MFA: "phishing_mfa",
  DOMAIN_ACCOUNT: "domain_account",
  DNS_TUNNELING: "dns_tunneling",
};

const PREDEFINED_PROFILE_MAP = {
  "credential-theft-risk-chain": PROFILE_IDS.PHISHING_MFA,
  "pass-the-hash-spread": PROFILE_IDS.PASS_THE_HASH,
  "kerberos-ticket-follow-on": PROFILE_IDS.KERBEROS_TICKET,
  "dns-tunneling-artifact-risk": PROFILE_IDS.DNS_TUNNELING,
  "domain-account-compromise-risk": PROFILE_IDS.DOMAIN_ACCOUNT,
};

function createProfile(config) {
  return {
    displayCategory: "Genel tehdit yorumu",
    canonicalAttackName: "",
    summaryStrategy: "risk_spread_defense",
    riskPriorities: [],
    preferredArtifactCategories: [],
    preferredTacticEmphasis: [],
    preferredNextTacticEmphasis: [],
    immediateActionStrategy: "contain_validate_hunt",
    defenseEmphasisStrategy: "graph_first",
    forbiddenSummaryPatterns: [],
    semanticFallbackHints: [],
    backendAttackNames: [],
    aliases: [],
    ...config,
  };
}

const scenarioProfiles = {
  [PROFILE_IDS.DNS_ATTACK]: createProfile({
    id: PROFILE_IDS.DNS_ATTACK,
    canonicalAttackName: "DNS Attack",
    displayCategory: "DNS tabanlı saldırı",
    aliases: ["dns saldırısı", "dns attack", "dns abuse", "anormal dns", "şüpheli dns", "dns lookup"],
    backendAttackNames: ["dns", "dns attack", "dns lookup"],
    summaryStrategy: "dns_signal_chain",
    riskPriorities: ["örtük komut aktarımı", "şüpheli dış DNS iletişimi", "olası veri sızdırma"],
    preferredArtifactCategories: ["dns", "network", "process", "host", "session"],
    preferredTacticEmphasis: ["Command and Control", "Exfiltration", "Collection", "Discovery"],
    preferredNextTacticEmphasis: ["Exfiltration", "Command and Control", "Collection"],
    immediateActionStrategy: "dns_contain_and_trace",
    defenseEmphasisStrategy: "network_control_and_visibility",
    forbiddenSummaryPatterns: ["genel erişim genişlemesi", "soyut risk tablosu"],
    semanticFallbackHints: ["alan adı", "dns sorgu", "resolver", "name server"],
  }),
  [PROFILE_IDS.DYNAMIC_RESOLUTION]: createProfile({
    id: PROFILE_IDS.DYNAMIC_RESOLUTION,
    canonicalAttackName: "Dynamic Resolution",
    displayCategory: "Dinamik çözümleme kötüye kullanımı",
    aliases: ["dynamic resolution", "dynamic-resolution", "dinamik çözümleme", "resolution change", "name resolution"],
    backendAttackNames: ["dynamic resolution"],
    summaryStrategy: "resolution_indirection",
    riskPriorities: ["altyapı yönlendirme değişiklikleri", "şüpheli isim çözümleme zinciri", "geri çağrı ve yönlendirme riski"],
    preferredArtifactCategories: ["dns", "network", "process", "host"],
    preferredTacticEmphasis: ["Command and Control", "Discovery", "Defense Evasion"],
    preferredNextTacticEmphasis: ["Command and Control", "Collection", "Exfiltration"],
    immediateActionStrategy: "resolution_validation",
    defenseEmphasisStrategy: "visibility_and_domain_validation",
    forbiddenSummaryPatterns: ["genel kimlik riski"],
    semanticFallbackHints: ["resolution", "lookup path", "dns redirect", "callback domain"],
  }),
  [PROFILE_IDS.NETWORK_SNIFFING]: createProfile({
    id: PROFILE_IDS.NETWORK_SNIFFING,
    canonicalAttackName: "Network Sniffing",
    displayCategory: "Ağ dinleme / trafik yakalama",
    aliases: ["network sniffing", "network sniffer", "sniffing", "packet capture", "trafik dinleme", "ağ dinleme"],
    backendAttackNames: ["network sniffing", "sniffing"],
    summaryStrategy: "credential_exposure",
    riskPriorities: ["paket yakalama", "oturum ele geçirme riski", "açık iletişim sızıntısı"],
    preferredArtifactCategories: ["network", "credential", "session", "account"],
    preferredTacticEmphasis: ["Credential Access", "Collection", "Discovery"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Credential Access", "Collection"],
    immediateActionStrategy: "network_segment_and_rotate",
    defenseEmphasisStrategy: "credential_protection",
    forbiddenSummaryPatterns: ["dns trafiği", "dns sorgu bağlamı", "çözümleme zinciri"],
    semanticFallbackHints: ["packet", "capture", "intercept", "session hijack", "plaintext", "mirrored traffic"],
  }),
  [PROFILE_IDS.SESSION_HIJACKING]: createProfile({
    id: PROFILE_IDS.SESSION_HIJACKING,
    canonicalAttackName: "Session Hijacking",
    displayCategory: "Oturum ele geçirme",
    aliases: ["session hijacking", "browser session hijacking", "cookie hijacking"],
    backendAttackNames: ["session hijacking", "cookie hijacking"],
    summaryStrategy: "session_token_replay",
    riskPriorities: ["çalınmış oturum belirteçleri", "tarayıcı oturumu devralma", "token tekrar kullanımı"],
    preferredArtifactCategories: ["session", "token", "account", "authentication"],
    preferredTacticEmphasis: ["Credential Access", "Initial Access", "Defense Evasion"],
    preferredNextTacticEmphasis: ["Persistence", "Lateral Movement", "Collection"],
    immediateActionStrategy: "account_and_token_response",
    defenseEmphasisStrategy: "identity_containment",
    semanticFallbackHints: ["session token", "cookie replay", "browser session", "stolen cookie"],
  }),
  [PROFILE_IDS.CREDENTIAL_THEFT]: createProfile({
    id: PROFILE_IDS.CREDENTIAL_THEFT,
    canonicalAttackName: "Credential Theft",
    displayCategory: "Kimlik bilgisi hırsızlığı",
    aliases: ["credential theft", "credential harvesting"],
    backendAttackNames: ["credential theft", "credential harvesting"],
    summaryStrategy: "stolen_identity_chain",
    riskPriorities: ["çalınmış kimlik bilgilerinin yayılması", "yeniden kullanılan kimlikler", "ayrıcalık yükseltme zinciri"],
    preferredArtifactCategories: ["credential", "account", "session", "authentication"],
    preferredTacticEmphasis: ["Credential Access", "Privilege Escalation", "Lateral Movement"],
    preferredNextTacticEmphasis: ["Privilege Escalation", "Lateral Movement", "Persistence"],
    immediateActionStrategy: "credential_reset_and_scope",
    defenseEmphasisStrategy: "credential_hardening",
    semanticFallbackHints: ["harvested credential", "stolen identity", "credential exposure"],
  }),
  [PROFILE_IDS.EXPLOITATION_REMOTE_SERVICES]: createProfile({
    id: PROFILE_IDS.EXPLOITATION_REMOTE_SERVICES,
    canonicalAttackName: "Exploitation of Remote Services",
    displayCategory: "Uzak servis istismarı",
    aliases: ["exploitation of remote services", "remote services exploitation"],
    backendAttackNames: ["exploitation of remote services", "remote services exploitation"],
    summaryStrategy: "remote_service_compromise",
    riskPriorities: ["açık uzak servisler", "zafiyetli uzak uç noktalar", "servis üzerinden yanal ele geçirme"],
    preferredArtifactCategories: ["remote_service", "service", "host", "account"],
    preferredTacticEmphasis: ["Initial Access", "Lateral Movement", "Execution"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Privilege Escalation", "Persistence"],
    immediateActionStrategy: "remote_reuse_containment",
    defenseEmphasisStrategy: "remote_auth_control",
    semanticFallbackHints: ["remote service exploit", "service exploitation", "vulnerable endpoint"],
  }),
  [PROFILE_IDS.EXTERNAL_REMOTE_SERVICES]: createProfile({
    id: PROFILE_IDS.EXTERNAL_REMOTE_SERVICES,
    canonicalAttackName: "External Remote Services",
    displayCategory: "Dışa açık uzak erişim kötüye kullanımı",
    aliases: ["external remote services", "public remote access abuse"],
    backendAttackNames: ["external remote services", "public remote access abuse"],
    summaryStrategy: "internet_facing_remote_access",
    riskPriorities: ["VPN veya RDP dış erişim kötüye kullanımı", "internete açık servis yüzeyi", "uzak giriş noktalarından yetkisiz erişim"],
    preferredArtifactCategories: ["remote_service", "service", "account", "network"],
    preferredTacticEmphasis: ["Initial Access", "Credential Access", "Lateral Movement"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Persistence", "Privilege Escalation"],
    immediateActionStrategy: "remote_reuse_containment",
    defenseEmphasisStrategy: "remote_auth_control",
    semanticFallbackHints: ["internet-facing remote", "public remote access", "vpn abuse", "external rdp"],
  }),
  [PROFILE_IDS.RESOURCE_FORKING]: createProfile({
    id: PROFILE_IDS.RESOURCE_FORKING,
    canonicalAttackName: "Resource Forking",
    displayCategory: "Kaynak çatallama ve gizli yürütme",
    aliases: ["resource forking"],
    backendAttackNames: ["resource forking"],
    summaryStrategy: "deceptive_process_branching",
    riskPriorities: ["çatallanmış süreç zincirleri", "gizlenmiş yürütme dalları", "aldatıcı kaynak çoğaltımı"],
    preferredArtifactCategories: ["process", "host", "service"],
    preferredTacticEmphasis: ["Execution", "Defense Evasion", "Persistence"],
    preferredNextTacticEmphasis: ["Defense Evasion", "Persistence", "Lateral Movement"],
    immediateActionStrategy: "contain_validate_hunt",
    defenseEmphasisStrategy: "control_recovery",
    semanticFallbackHints: ["forked process", "hidden branch", "spawned resource", "duplicate execution"],
  }),
  [PROFILE_IDS.PASSWORD_CRACKING]: createProfile({
    id: PROFILE_IDS.PASSWORD_CRACKING,
    canonicalAttackName: "Password Cracking",
    displayCategory: "Parola kırma",
    aliases: ["password cracking", "password crack", "hash cracking", "parola kırma", "şifre kırma", "offline cracking"],
    backendAttackNames: ["password cracking"],
    summaryStrategy: "credential_compromise",
    riskPriorities: ["yeniden kullanılan sırlar", "hedefli kimlik ele geçirme", "takip eden erişim denemeleri"],
    preferredArtifactCategories: ["credential", "account", "authentication"],
    preferredTacticEmphasis: ["Credential Access"],
    preferredNextTacticEmphasis: ["Initial Access", "Persistence", "Lateral Movement"],
    immediateActionStrategy: "credential_reset_and_scope",
    defenseEmphasisStrategy: "credential_hardening",
    semanticFallbackHints: ["hash", "offline", "kırılmış parola"],
  }),
  [PROFILE_IDS.PASSWORD_GUESSING]: createProfile({
    id: PROFILE_IDS.PASSWORD_GUESSING,
    canonicalAttackName: "Password Guessing",
    displayCategory: "Parola tahmini",
    aliases: ["password guessing", "password guess", "guessing", "parola tahmini", "şifre tahmini", "credential guessing"],
    backendAttackNames: ["password guessing"],
    summaryStrategy: "authentication_pressure",
    riskPriorities: ["tekrarlı kimlik doğrulama denemeleri", "hedefli hesap baskısı", "başarılı giriş sonrası yayılım"],
    preferredArtifactCategories: ["account", "authentication", "credential", "session"],
    preferredTacticEmphasis: ["Credential Access", "Initial Access"],
    preferredNextTacticEmphasis: ["Persistence", "Lateral Movement", "Defense Evasion"],
    immediateActionStrategy: "guessing_triage",
    defenseEmphasisStrategy: "account_protection",
    forbiddenSummaryPatterns: ["token odaklı varsayım"],
    semanticFallbackHints: ["failed login", "auth attempt", "çoklu giriş denemesi"],
  }),
  [PROFILE_IDS.PASSWORD_SPRAYING]: createProfile({
    id: PROFILE_IDS.PASSWORD_SPRAYING,
    canonicalAttackName: "Password Spraying",
    displayCategory: "Parola spraying",
    aliases: ["password spraying", "password spray", "spraying", "parola spraying", "çoklu hesap tahmini"],
    backendAttackNames: ["password spraying"],
    summaryStrategy: "broad_auth_surface",
    riskPriorities: ["çok hesaplı düşük frekanslı hedefleme", "kurumsal giriş yüzeyi baskısı", "başarılı girişlerle yayılım"],
    preferredArtifactCategories: ["account", "authentication", "remote_service", "credential"],
    preferredTacticEmphasis: ["Credential Access", "Initial Access"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Persistence", "Privilege Escalation"],
    immediateActionStrategy: "spraying_scope_and_protect",
    defenseEmphasisStrategy: "identity_surface_protection",
    semanticFallbackHints: ["many accounts", "broad auth", "multi user"],
  }),
  [PROFILE_IDS.DISABLE_OR_MODIFY_TOOLS]: createProfile({
    id: PROFILE_IDS.DISABLE_OR_MODIFY_TOOLS,
    canonicalAttackName: "Disable or Modify Tools",
    displayCategory: "Savunma zayıflatma / araç manipülasyonu",
    aliases: ["disable or modify tools", "disable tools", "modify tools", "security tool tampering", "güvenlik aracını devre dışı bırakma", "araçları devre dışı bırakma", "araçları değiştirme"],
    backendAttackNames: ["disable or modify tools"],
    summaryStrategy: "defense_visibility_loss",
    riskPriorities: ["devre dışı bırakılan güvenlik ajanları", "izleme kör noktaları", "telemetri kesintisi"],
    preferredArtifactCategories: ["security_tool", "process", "host", "control"],
    preferredTacticEmphasis: ["Defense Evasion", "Impact", "Execution"],
    preferredNextTacticEmphasis: ["Persistence", "Credential Access", "Lateral Movement"],
    immediateActionStrategy: "restore_controls_and_hunt",
    defenseEmphasisStrategy: "control_recovery",
    forbiddenSummaryPatterns: ["kalıcılık süreçleri", "scheduled execution tone"],
    semanticFallbackHints: ["tamper", "disable av", "disable edr", "monitoring loss", "telemetry interruption", "security agent shutdown"],
  }),
  [PROFILE_IDS.SCHEDULED_TASK]: createProfile({
    id: PROFILE_IDS.SCHEDULED_TASK,
    canonicalAttackName: "Scheduled Task/Job",
    displayCategory: "Zamanlanmış görev kalıcılığı",
    aliases: ["scheduled task", "scheduled task/job", "scheduled job", "task scheduler", "zamanlanmış görev", "zamanlanmış iş"],
    backendAttackNames: ["scheduled task", "scheduled task/job"],
    summaryStrategy: "persistence_reentry",
    riskPriorities: ["yetkisiz görev oluşturma", "tekrarlayan tetikleyici zincirleri", "kalıcılık amaçlı yeniden çalıştırma döngüleri"],
    preferredArtifactCategories: ["scheduled_task", "process", "host", "account"],
    preferredTacticEmphasis: ["Persistence", "Execution", "Privilege Escalation"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Collection", "Credential Access"],
    immediateActionStrategy: "scheduled_task_cleanup",
    defenseEmphasisStrategy: "persistence_control",
    forbiddenSummaryPatterns: ["genel parola riski"],
    semanticFallbackHints: ["task scheduler", "cron benzeri", "tekrarlı çalıştırma"],
  }),
  [PROFILE_IDS.KERBEROS_TICKET]: createProfile({
    id: PROFILE_IDS.KERBEROS_TICKET,
    canonicalAttackName: "Kerberos Ticket",
    displayCategory: "Kerberos ticket kötüye kullanımı",
    aliases: ["kerberos", "kerberos ticket", "golden ticket", "silver ticket", "kerberos bileti"],
    backendAttackNames: ["kerberos", "kerberos ticket"],
    summaryStrategy: "trusted_auth_reuse",
    riskPriorities: ["güvenilen kimlik bağlamının yeniden kullanımı", "ayrıcalıklı servis erişimi", "ticket tabanlı oturumlar"],
    preferredArtifactCategories: ["session", "account", "credential", "service", "authentication"],
    preferredTacticEmphasis: ["Credential Access", "Lateral Movement", "Privilege Escalation"],
    preferredNextTacticEmphasis: ["Privilege Escalation", "Lateral Movement", "Collection"],
    immediateActionStrategy: "ticket_session_containment",
    defenseEmphasisStrategy: "trusted_auth_control",
    semanticFallbackHints: ["service ticket", "tgt", "tgs"],
  }),
  [PROFILE_IDS.PASS_THE_HASH]: createProfile({
    id: PROFILE_IDS.PASS_THE_HASH,
    canonicalAttackName: "Pass-the-Hash",
    displayCategory: "Kimlik materyali yeniden kullanımı",
    aliases: ["pass-the-hash", "pass the hash", "pth", "hash reuse", "hash ile giriş"],
    backendAttackNames: ["pass-the-hash", "pass the hash"],
    summaryStrategy: "remote_auth_reuse",
    riskPriorities: ["uzak kimlik doğrulama tekrar kullanımı", "host zinciri boyunca yanal yayılım", "yönetim yüzeyi istismarı"],
    preferredArtifactCategories: ["credential", "session", "remote_service", "host", "account"],
    preferredTacticEmphasis: ["Lateral Movement", "Credential Access", "Privilege Escalation"],
    preferredNextTacticEmphasis: ["Privilege Escalation", "Collection", "Impact"],
    immediateActionStrategy: "remote_reuse_containment",
    defenseEmphasisStrategy: "remote_auth_control",
    semanticFallbackHints: ["smb", "winrm", "psexec", "remote logon"],
  }),
  [PROFILE_IDS.DCSYNC]: createProfile({
    id: PROFILE_IDS.DCSYNC,
    canonicalAttackName: "DCSync",
    displayCategory: "Directory replication kötüye kullanımı",
    aliases: ["dcsync", "dc sync", "directory replication", "replication abuse"],
    backendAttackNames: ["dcsync"],
    summaryStrategy: "directory_replication_abuse",
    riskPriorities: ["domain replication abuse", "KRBTGT riski", "ayrıcalıklı replication hesapları"],
    preferredArtifactCategories: ["account", "service", "host", "credential"],
    preferredTacticEmphasis: ["Credential Access", "Privilege Escalation", "Discovery"],
    preferredNextTacticEmphasis: ["Privilege Escalation", "Lateral Movement", "Persistence"],
    immediateActionStrategy: "dcsync_containment",
    defenseEmphasisStrategy: "trusted_auth_control",
    semanticFallbackHints: ["replication rights", "getncchanges", "krbtgt", "domain controller replication"],
  }),
  [PROFILE_IDS.LSASS_MEMORY]: createProfile({
    id: PROFILE_IDS.LSASS_MEMORY,
    canonicalAttackName: "LSASS Memory",
    displayCategory: "LSASS bellek erişimi",
    aliases: ["lsass memory", "lsass dump", "lsass access", "memory dump of lsass"],
    backendAttackNames: ["lsass memory"],
    summaryStrategy: "lsass_memory_access",
    riskPriorities: ["lsass dump işlemleri", "handle erişimi", "credential extraction"],
    preferredArtifactCategories: ["process", "credential", "host", "account"],
    preferredTacticEmphasis: ["Credential Access", "Defense Evasion", "Execution"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Privilege Escalation", "Persistence"],
    immediateActionStrategy: "lsass_memory_response",
    defenseEmphasisStrategy: "credential_hardening",
    semanticFallbackHints: ["lsass", "sekurlsa", "comsvcs", "mini dump"],
  }),
  [PROFILE_IDS.CREDENTIAL_DUMPING]: createProfile({
    id: PROFILE_IDS.CREDENTIAL_DUMPING,
    canonicalAttackName: "Credential Dumping",
    displayCategory: "Kimlik dökümü çıkarma",
    aliases: ["credential dumping", "credential dump", "dump credentials"],
    backendAttackNames: ["credential dumping"],
    summaryStrategy: "credential_dumping_chain",
    riskPriorities: ["credential vault erişimi", "dumped secrets", "token kötüye kullanımı"],
    preferredArtifactCategories: ["credential", "process", "account", "host"],
    preferredTacticEmphasis: ["Credential Access", "Privilege Escalation", "Lateral Movement"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Privilege Escalation", "Persistence"],
    immediateActionStrategy: "credential_dumping_response",
    defenseEmphasisStrategy: "credential_hardening",
    semanticFallbackHints: ["credential dumping", "vault sweep", "dumped secret", "sam dump"],
  }),
  [PROFILE_IDS.RDP_HIJACKING]: createProfile({
    id: PROFILE_IDS.RDP_HIJACKING,
    canonicalAttackName: "RDP Hijacking",
    displayCategory: "RDP oturum ele geçirme",
    aliases: ["rdp hijacking", "rdp session hijacking", "remote desktop hijacking"],
    backendAttackNames: ["rdp hijacking"],
    summaryStrategy: "rdp_session_takeover",
    riskPriorities: ["active RDP oturumları", "session ownership drift", "remote host erişimi"],
    preferredArtifactCategories: ["remote_service", "session", "host", "account"],
    preferredTacticEmphasis: ["Lateral Movement", "Credential Access", "Defense Evasion"],
    preferredNextTacticEmphasis: ["Privilege Escalation", "Collection", "Persistence"],
    immediateActionStrategy: "rdp_hijack_response",
    defenseEmphasisStrategy: "remote_auth_control",
    semanticFallbackHints: ["rdp hijack", "shadow session", "tscon", "remote desktop session"],
  }),
  [PROFILE_IDS.PHISHING_MFA]: createProfile({
    id: PROFILE_IDS.PHISHING_MFA,
    canonicalAttackName: "Phishing",
    displayCategory: "Kimlik bilgisi / MFA ele geçirme",
    aliases: ["phishing", "mfa token", "token theft", "session cookie theft", "kimlik bilgisi ele geçirme", "mfa ele geçirme"],
    backendAttackNames: ["phishing", "adversary in the middle", "mfa interception"],
    summaryStrategy: "account_takeover",
    riskPriorities: ["hesap devralma", "token veya oturum kötüye kullanımı", "yetkisiz servis erişimi"],
    preferredArtifactCategories: ["account", "credential", "session", "token", "remote_service"],
    preferredTacticEmphasis: ["Initial Access", "Credential Access", "Persistence"],
    preferredNextTacticEmphasis: ["Lateral Movement", "Collection", "Privilege Escalation"],
    immediateActionStrategy: "account_and_token_response",
    defenseEmphasisStrategy: "identity_containment",
    semanticFallbackHints: ["oturum çerezi", "session cookie", "idp", "new device"],
  }),
  [PROFILE_IDS.DOMAIN_ACCOUNT]: createProfile({
    id: PROFILE_IDS.DOMAIN_ACCOUNT,
    canonicalAttackName: "Domain Account Compromise",
    displayCategory: "Domain hesabının ele geçirilmesi",
    aliases: ["domain account compromise", "domain account", "domain hesabı", "compromised domain account"],
    backendAttackNames: ["domain account compromise", "domain account"],
    summaryStrategy: "shared_service_spread",
    riskPriorities: ["paylaşımlı servis erişimi", "çapraz host oturumları", "ayrıcalık yüzeyi genişlemesi"],
    preferredArtifactCategories: ["account", "session", "service", "host", "remote_service"],
    preferredTacticEmphasis: ["Lateral Movement", "Privilege Escalation", "Persistence"],
    preferredNextTacticEmphasis: ["Credential Access", "Collection", "Impact"],
    immediateActionStrategy: "account_scope_containment",
    defenseEmphasisStrategy: "privilege_reduction",
    semanticFallbackHints: ["shared service", "domain login", "admin surface"],
  }),
  [PROFILE_IDS.DNS_TUNNELING]: createProfile({
    id: PROFILE_IDS.DNS_TUNNELING,
    canonicalAttackName: "DNS Tunneling",
    displayCategory: "DNS tünelleme",
    aliases: ["dns tunneling", "dns tunnel", "dns tünelleme", "dns tüneli"],
    backendAttackNames: ["dns tunneling"],
    summaryStrategy: "dns_exfiltration",
    riskPriorities: ["gizli haberleşme", "veri sızdırma", "düşük görünürlüklü komut aktarımı"],
    preferredArtifactCategories: ["dns", "network", "process", "host", "session"],
    preferredTacticEmphasis: ["Command and Control", "Exfiltration", "Collection"],
    preferredNextTacticEmphasis: ["Exfiltration", "Collection", "Impact"],
    immediateActionStrategy: "dns_tunnel_response",
    defenseEmphasisStrategy: "network_control_and_visibility",
    semanticFallbackHints: ["encoded query", "uzun dns sorgu", "dns exfiltration"],
  }),
  [PROFILE_IDS.GENERIC]: createProfile({
    id: PROFILE_IDS.GENERIC,
    displayCategory: "Genel senaryo yorumu",
    summaryStrategy: "balanced_generic",
    riskPriorities: ["erişim genişlemesi", "ilişkili varlık etkisi", "takip eden taktik riski"],
    preferredArtifactCategories: ["host", "process", "account", "network"],
  }),
};

function getScenarioProfile(profileId) {
  return scenarioProfiles[profileId] || scenarioProfiles[PROFILE_IDS.GENERIC];
}

export { PREDEFINED_PROFILE_MAP, PROFILE_IDS, getScenarioProfile, scenarioProfiles };
